import type { PlanModule } from '@/lib/types'

export const DEMO_CLIENT = {
  full_name: 'Petr Novák',
  age: 38,
}

export const DEMO_ADVISOR = 'Jakub Jevčák · Profiplán'

export const DEMO_MODULES: PlanModule[] = [
  {
    id: 'd1',
    plan_id: 'demo',
    module_type: 'income_protection_1',
    slot: 1,
    pdf_url: null,
    is_verified: true,
    created_at: '',
    extracted_data: null,
    manual_override: {
      pojistovna: 'Allianz pojišťovna',
      mesicni_pojistne: 1250,
      pojistna_castka: 2000000,
      platnost_od: '2026-06-01',
      platnost_do: '2046-06-01',
      kryti_rizika: ['Smrt úrazem', 'Trvalé následky', 'Hospitalizace', 'Pracovní neschopnost'],
      cekaci_doba: '3 měsíce',
      karence: '14 dní',
      indexace: 'Ano, 3% ročně',
    },
  },
  {
    id: 'd2',
    plan_id: 'demo',
    module_type: 'income_protection_2',
    slot: 2,
    pdf_url: null,
    is_verified: true,
    created_at: '',
    extracted_data: null,
    manual_override: {
      pojistovna: 'NN pojišťovna',
      mesicni_pojistne: 980,
      pojistna_castka: 1500000,
      platnost_od: '2026-06-01',
      platnost_do: '2046-06-01',
      kryti_rizika: ['Smrt z jakékoli příčiny', 'Invalidita 3. stupně', 'Závažná onemocnění'],
      cekaci_doba: '2 měsíce',
      karence: '21 dní',
      indexace: 'Ne',
    },
  },
  {
    id: 'd3',
    plan_id: 'demo',
    module_type: 'pension',
    slot: 1,
    pdf_url: null,
    is_verified: true,
    created_at: '',
    extracted_data: null,
    manual_override: {
      instituce: 'Conseq doplňkové penzijní spoření',
      mesicni_prispevek: 1500,
      statni_prispevek: 230,
      zamestnavatelsky_prispevek: 1500,
      predpokladana_renta: 18500,
      vek_odchodu: 67,
      zhodnoceni_pa: 5.2,
    },
  },
  {
    id: 'd4',
    plan_id: 'demo',
    module_type: 'mortgage',
    slot: 1,
    pdf_url: null,
    is_verified: true,
    created_at: '',
    extracted_data: null,
    manual_override: {
      banka: 'Česká spořitelna',
      vyse_uveru: 4500000,
      mesicni_splatka: 22800,
      urokova_sazba: 4.69,
      doba_splaceni: 25,
      ltv: 80,
      fixace: '5 let',
    },
  },
  {
    id: 'd5',
    plan_id: 'demo',
    module_type: 'children_investment',
    slot: 1,
    pdf_url: null,
    is_verified: true,
    created_at: '',
    extracted_data: null,
    manual_override: {
      instituce: 'Portu — dětský účet',
      mesicni_vklad: 2000,
      predpokladane_zhodnoceni: 7.5,
      investicni_horizont: 15,
      cilova_castka: 650000,
    },
  },
  {
    id: 'd6',
    plan_id: 'demo',
    module_type: 'free_investment',
    slot: 1,
    pdf_url: null,
    is_verified: true,
    created_at: '',
    extracted_data: null,
    manual_override: {
      instituce: 'Trigea nemovitostní fond',
      mesicni_vklad: 5000,
      predpokladane_zhodnoceni: 6.8,
      investicni_horizont: 20,
      cilova_castka: 2500000,
    },
  },
]
